---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: how to set up object storage in astra, how to set up astra buckets, s3, astra, setting up astra control, how to set up astra control center, kubernetes 
summary: 如果您想要備份應用程式及持續儲存的應用程式、而且想要跨叢集複製應用程式、則必須新增物件存放區資源庫供應商。 
---
= 管理儲存庫
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


如果您想要備份應用程式和持續儲存設備、或是想要跨叢集複製應用程式、物件存放區供應商是不可或缺的。使用Astra Control Center、新增物件存放區供應商做為您的應用程式離叢集備份目的地。

如果您要將應用程式組態和持續儲存設備複製到同一個叢集、則不需要儲存庫。

請使用下列任何一種庫位供應商：

* NetApp ONTAP 產品S3
* NetApp StorageGRID 產品S3
* 一般S3



NOTE: 雖然Astra Control Center支援Amazon S3做為通用S3儲存區供應商、但Astra Control Center可能不支援所有聲稱Amazon S3支援的物件儲存區廠商。

您無法刪除儲存區、不過您可以加以編輯。

儲存庫可以位於下列其中一種狀態：

* 擱置中：已排定要探索的儲存區。
* 可用：鏟斗可供使用。
* 已移除：目前無法存取儲存貯體。


如需如何使用Astra Control API管理儲存區的指示、請參閱 link:https://docs.netapp.com/us-en/astra-automation/["Astra Automation和API資訊"^]。

您可以執行與管理儲存庫相關的工作：

* link:../get-started/setup_overview.html#add-a-bucket["新增儲存庫"]
*  a bucket



NOTE: Astra Control Center中的S3鏟斗未報告可用容量。在備份或複製由Astra Control Center管理的應用程式之前、請先查看ONTAP 資訊庫（英文）或StorageGRID 資訊庫（英文）管理系統中的庫位資訊。



== 移除認證資料

使用Astra Control API、隨時從帳戶移除S3認證。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/astra-automation/index.html["使用Astra Control API"^]。


TIP: 您新增至Astra Control的第一組認證資料一律使用中、因為Astra Control使用認證資料來驗證備份儲存區。最好不要移除這些認證資料。



== 編輯儲存庫

您可以變更儲存區的存取認證資訊、並變更所選儲存區是否為預設儲存區。


NOTE: 新增儲存庫時、請選擇正確的儲存庫供應商、並提供該供應商的適當認證資料。例如、UI接受NetApp ONTAP S3作為類型並接受StorageGRID 驗證、但這將導致所有未來使用此儲存庫的應用程式備份與還原失敗。請參閱 link:../release-notes/known-issues.html#selecting-a-bucket-provider-type-with-credentials-for-another-type-causes-data-protection-failures["版本資訊"]。

.步驟
. 從左側導覽中選取*鏟斗*。
. 從「動作」功能表中選取*「編輯」*。
. 變更儲存桶類型以外的任何資訊。
+

TIP: 您無法修改貯體類型。

. 選擇*更新*。




== 如需詳細資訊、請參閱

* https://docs.netapp.com/us-en/astra-automation/index.html["使用Astra Control API"^]

